version: "3.9"
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - DJANGO_SECRET_KEY=dev-secret-key
      - DEBUG=1
    ports:
      - "8000:8000"
    command: ["bash", "-c", "python manage.py migrate && gunicorn api_project.wsgi:application --bind 0.0.0.0:8000"]

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: ["bash", "-c", "npm run build && npm run start"]
