# Generated by Django 5.2.7 on 2025-10-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_team_size', models.PositiveIntegerField(default=1)),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.fest')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.fest')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.item')),
            ],
        ),
    ]
