name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root deps
        run: npm install
      - name: Lint web
        run: npm run lint -w apps/web
      - name: Build web
        run: npm run build -w apps/web

  api_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        working-directory: apps/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django system checks
        working-directory: apps/api
        run: |
          python manage.py check --deploy --fail-level ERROR
      - name: Migrations dry run
        working-directory: apps/api
        run: |
          python manage.py makemigrations --check --dry-run

  docker_build:
    runs-on: ubuntu-latest
    needs: [web_build, api_check]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: docker build -t aifest/api:ci ./apps/api
      - name: Build Web image
        run: docker build -t aifest/web:ci ./apps/web
